name: "Repository Mirror: Music App"

on: workflow_dispatch

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Mirror"
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Clone repository"
        shell: bash
        run: git clone --bare https://lukas-eisenhauer.de/git/git/lukas/music.git
      - name: "pushing mirrored repository"
        shell: bash
        run: cd music.git && git push --mirror git@github.com:biosfood/music-app.git
